service: test-service-bodhi

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: dist/handler.getActStatus
    events:
      - http:
          path: getActStatus
          method: get